add comparison
linode/linodego pull request #145
Opened 2020-05-05 17:06 UTC by zdypro888

### General:

* [ ] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [ ] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

### Pull Request Guidelines:

1. [ ] Does your submission pass tests?
1. [ ] Have you added tests? 
1. [ ] Are you addressing a single feature in this PR? 
1. [ ] Are your commits atomic, addressing one change per commit?
1. [ ] Are you following the conventions of the language? 
1. [ ] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [ ] Have you explained your rationale for why this feature is needed? 
1. [ ] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)

2020-05-06 14:43 UTC, phillc commented
Hello,
This is an interesting idea. We are circulating this internally for feedback. Thank you for the PR!

2021-09-16 18:08 UTC, LBGarber requested changes
I love this idea! Here are a few ways we can simplify the logic.

2021-09-16 18:08 UTC, LBGarber commented on comparison.go
> +}
```suggestion
func (c *Comparison) JSON() string {
	if c.Operator == Eq {
		return fmt.Sprintf("{\"%s\": %s}", c.Column, getJSONValueString(c.Value))
	}

	return fmt.Sprintf("{\"%s\": {\"%s\": %v}",
		c.Column, c.Operator, getJSONValueString(c.Value))
}

2021-09-16 18:08 UTC, LBGarber commented on comparison.go
> +}
```suggestion
}

func getJSONValueString(value interface{}) string {
	if _, ok := value.(string); ok {
		return fmt.Sprintf("\"%s\"", value)
	}

	return fmt.Sprintf("%v", value)
}
```

2021-09-16 18:12 UTC, LBGarber approved these changes
Looks good!!

2021-09-16 18:17 UTC, merged