Use mocks for TestInstanceStats_Get and TestObjectStorage_Cancel tests
linode/linodego pull request #427
Opened 2023-11-15 21:12 UTC by amisiorek-akamai

## 📝 Description

Makes mocks for TestInstanceStats_Get and TestObjectStorage_Cancel such that we no longer have to skip those tests.

## ✔️ How to Test

`make test SKIP_LINT=1 ARGS="-run TestInstanceStats_Get"`

`make test SKIP_LINT=1 ARGS="-run TestObjectStorage_Cancel"`

2023-11-16 16:16 UTC, zliang-akamai commented
Can we create a unit test directory to hold all mocked tests or maybe making a `xxxx_test.go` file in the root directory of the repo (like [this one](https://github.com/linode/linodego/blob/main/client_test.go))?

2023-11-16 19:22 UTC, zliang-akamai commented
@amisiorek-akamai Ah yes, your are right, didn't realize that, lol

2023-11-17 06:52 UTC, zliang-akamai approved these changes
Tested locally and passed!

2023-11-17 15:59 UTC, lgarber-akamai requested changes

2023-11-17 15:59 UTC, lgarber-akamai commented on test/integration/instance_stats_test.go
> +		},
Could this be populated with some arbitrary data just to make sure everything unmarshals correctly?

2023-11-17 18:35 UTC, lgarber-akamai approved these changes
Looks good and tests pass locally, great work!

2023-11-17 18:36 UTC, merged